# Generated by Django 4.1.2 on 2022-11-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_img_alt_text',
            field=models.TextField(default='unison', max_length=50, null=True),
        ),
    ]
