# Generated by Django 4.1.2 on 2022-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactdata_contactnum_alter_contactdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
