# Generated by Django 4.1.2 on 2022-11-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactdata_email_alter_contactdata_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='contactNum',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
